//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.rs;

import com.hp.sdn.rs.misc.ControllerResource;

import java.util.UUID;

import java.util.ArrayList;
import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.DELETE;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.ResponseBuilder;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import com.a.hola.model.PHD;
import com.a.hola.api.PHDService;

import com.hp.api.Id;

/**
 * Sample PHD REST API resource.
 */
@Path("PHD")
public class PHDResource extends ControllerResource {

    /**
     * Gets JSON array of all PHD items.
     * <p>
     * Normal Response Code(s): ok (200)
     * <p>
     * Error Response Codes: unauthorized (401), forbidden (403), badMethod
     * (405), serviceUnavailable (503)
     * 
     * @return JSON array
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getAll() {
        PHDService svc = get(PHDService.class);

        ObjectMapper mapper = new ObjectMapper();
        ObjectNode root = mapper.createObjectNode();
        List<JsonNode> nodes = new ArrayList<JsonNode>();
        for (PHD s : svc.getAll())
            nodes.add(json(s, mapper));

        ArrayNode rowNode = root.putArray("PHD");
        rowNode.addAll(nodes);

        return ok(root.toString()).build();
    }

    /**
     * Creates a new PHD and registers it.
     * <p>
     * Normal Response Code(s): ok (200)
     * <p>
     * Error Response Codes: badRequest (400), unauthorized (401), forbidden (403), 
     * badMethod (405), serviceUnavailable (503)
     * 
     * @param request JSON representation of a PHD to be created
     * @return JSON object
     */
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    public Response create(String request) {
        PHDService svc = get(PHDService.class);

        // Decode request
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = parse(mapper, request, "PHD data");
        JsonNode node = root.path("item");
        
        String name = exists(node, "name") ? node.path("name").asText() : null;

        // Call the service
        PHD s = svc.create(name);

        // Encode response
        return response(s, mapper).build();
    }

    /**
     * Gets the specified PHD by its identifier.
     * <p>
     * Normal Response Code(s): ok (200)
     * <p>
     * Error Response Codes: badRequest (400), unauthorized (401), forbidden (403), 
     * badMethod (405), serviceUnavailable (503), itemNotFound (404)
     * 
     * @param uid the PHD unique identifier
     * @return JSON object
     */
    @GET
    @Path("{uid}")
    @Produces(MediaType.APPLICATION_JSON)
    public Response get(@PathParam("uid") String uid) {
        PHDService svc = get(PHDService.class);
        Id<PHD, UUID> id = Id.valueOf(UUID.fromString(uid));
        PHD s = svc.get(id);

        // Encode response
        return response(s, new ObjectMapper()).build();
    }

    /**
     * Deletes the specified PHD.
     * <p>
     * Normal Response Code(s): ok (200)
     * <p>
     * Error Response Codes: badRequest (400), unauthorized (401), forbidden (403), 
     * badMethod (405), serviceUnavailable (503), itemNotFound (404)
     * 
     * @param uid the PHD unique identifier
     * @return no data
     */
    @DELETE
    @Path("{uid}")
    @Produces(MediaType.APPLICATION_JSON)
    public Response delete(@PathParam("uid") String uid) {
        PHDService svc = get(PHDService.class);
        Id<PHD, UUID> id = Id.valueOf(UUID.fromString(uid));
        svc.delete(id);
        // Encode response
        return Response.ok().build();
    }

    // Encode the response builder for the specified PHD
    private ResponseBuilder response(PHD s, ObjectMapper mapper) {
        ObjectNode r = mapper.createObjectNode();
        r.put("item", json(s, mapper));
        return ok(r.toString());
    }

    /**
     * Returns JSON string describing the given PHD information.
     * 
     * @param s the PHD
     * @param mapper JSON object mapper
     * @return the JSON node representing the specified PHD information
     */
    static JsonNode json(PHD s, ObjectMapper mapper) {
        ObjectNode node = mapper.createObjectNode();
        node.put("uid", s.getId().getValue().toString());
        node.put("name", s.name());
        return node;
    }

}
