//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the PHD domain model.
 */
public class PHDTest {

    @Test
    public void basic() {
        Id<PHD, UUID> id = Id.valueOf(UUID.randomUUID());
        PHD s = new PHD(id, "Gizmo");
        assertEquals("incorrect id", id, s.getId());
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
