//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.model;

import java.util.UUID;

import com.hp.api.Id;

import com.hp.sdn.Model;

/**
 * Sample PHD domain model.
 */
public class PHD extends Model<PHD> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public PHD() {
        super();
    }

    /** 
     * Creates a new PHD entity. 
     *
     * @param name PHD name
     */
    public PHD(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new PHD entity. 
     *
     * @param id PHD unique id
     * @param name PHD name
     */
    public PHD(Id<PHD, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the PHD name.
     *
     * @return PHD name
     */
    public String name() {
        return name;
    }

    /**
     * Set the PHD name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
