//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.model;

/**
 * PHD sort attribute.
 */
public enum PHDSortAttribute {

    /** Sorts by name */
    NAME

}
