//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.rs;

import static org.easymock.EasyMock.createMock;
import static org.easymock.EasyMock.expect;
import static org.easymock.EasyMock.replay;
import static org.easymock.EasyMock.verify;

import java.util.UUID;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;

import javax.ws.rs.core.MediaType;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.hp.util.rs.ResourceTest;
import com.hp.sdn.rs.misc.ControllerResourceTest;

import com.a.hola.model.PHD;
import com.a.hola.api.PHDService;

import com.hp.api.Id;


/**
 * Sample PHD REST API resource.
 */
public class PHDResourceTest extends ControllerResourceTest {

    private PHDService svc;
    
    /**
     * Creates a test suite on the default package set.
     */
    public PHDResourceTest() {
        super("com.a.hola.rs");
    }
    

    @Override
    @Before
    public void setUp() throws Exception {
        super.setUp();
        svc = createMock(PHDService.class);

        sl.register(PHDService.class, svc,
                    Collections.<String, Object> emptyMap());

        // If a specific test case expects a different format, such
        // format will have to be set calling this method.
        ResourceTest.setDefaultMediaType(MediaType.APPLICATION_JSON);
    }
    
    @Override
    @After
    public void tearDown() throws Exception {
        super.tearDown();
        sl.unregister(PHDService.class, svc);
    }   

    @Test
    public void addPHD() {
        PHD s = new PHD("Thingie");
        
        expect(svc.create("Thingie"))
            .andReturn(s);
        replay(svc);
        
        String r = post("PHD",  
                        "{\"item\":{\"name\":\"Thingie\"}}");
        assertResponseContains(r, "\"uid\":\"" + s.getId().getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getPHD() {
        Id<PHD, UUID> id = Id.valueOf(UUID.randomUUID());
        
        expect(svc.get(id)).andReturn(new PHD(id, "Thingie"));
        replay(svc);
        
        String r = get("PHD/" + id.getValue());
        assertResponseContains(r, "\"uid\":\"" + id.getValue() + "\"", "\"name\":\"Thingie\"");
        verify(svc);
    }

    @Test
    public void getAll() {
        Id<PHD, UUID> id1 = Id.valueOf(UUID.randomUUID());
        Id<PHD, UUID> id2 = Id.valueOf(UUID.randomUUID());

        Collection<PHD> c = new HashSet<PHD>();
        c.add(new PHD(id1, "Thingie"));
        c.add(new PHD(id2, "Doo-Hickey"));
        expect(svc.getAll()).andReturn(c);
        replay(svc);

        String r = get("PHD");
        assertResponseContains(r, "\"PHD\":[",
                               "{\"uid\":\"" + id1.getValue() + "\"", "{\"uid\":\"" + id2.getValue() + "\"");
        verify(svc);
    }

    @Test
    public void deletePHD() {
        Id<PHD, UUID> id = Id.valueOf(UUID.randomUUID());
        
        svc.delete(id);
        replay(svc);
        
     //  String r = delete("PHD/" + id.getValue());
        verify(svc);
    }
}
