//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.api;

import java.util.UUID;

import com.a.hola.model.PHD;
import com.hp.api.NotFoundException;

import com.hp.api.Id;

import java.util.Collection;

/**
 * Sample PHD service interface.
 */
public interface PHDService {

    /**
     * Get all PHD items.
     *
     * @return collection of all PHD items
     */
    public Collection<PHD> getAll();

    /** 
     * Creates a new PHD entity.
     *
     * @param id unique id to be assigned to the new PHD entity.
     * @param name PHD name
     * @return newly created PHD
     */
    public PHD create(String name);

    /**
     * Get the PHD with the specified unique id.
     *
     * @param uid unique id of the PHD entity to be retrieved
     * @return PHD with the given unique id
     * @throws NotFoundException if the requested PHD was not found
     */
    public PHD get(Id<PHD, UUID> id);

    /**
     * Delete the PHD with the specified id.
     *
     * @param uid unique id of the PHD entity to be deleted
     * @return deleted PHD
     * @throws NotFoundException if the requested PHD was not found
     */
    public void delete(Id<PHD, UUID> id);

}
