//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.impl;

import java.util.UUID;


import static com.hp.util.StringUtils.isEmpty;

import com.a.hola.model.PHD;
import com.a.hola.api.PHDService;

import com.hp.api.NotFoundException;

import java.util.Map;
import java.util.HashMap;
import java.util.Collection;
import java.util.Collections;


import com.hp.api.Id;

import org.apache.felix.scr.annotations.Component;
import org.apache.felix.scr.annotations.Service;

/**
 * Sample PHD service implementation.
 */
@Component
@Service
public class PHDManager implements PHDService {

    // Just for kicks in-memory store.
    private static final Map<Id<PHD, UUID>, PHD> store = 
        new HashMap<Id<PHD, UUID>, PHD>();

    @Override
    public Collection<PHD> getAll() {
        synchronized (store) {
            return Collections.unmodifiableCollection(store.values());
        }
    }

    @Override
    public PHD create(String name) {
        synchronized (store) {
            PHD s = new PHD(name);
            if(isEmpty(s.name())){
                s.setName("PHD-" + s.getId().getValue().toString());
            }
            store.put(s.getId(), s);
            return s;
        }
    }

    @Override
    public PHD get(Id<PHD, UUID> id) {
        synchronized (store) {
            PHD s = store.get(id);
            if (s == null)
                throw new NotFoundException("PHD with id " + id + 
                                            " not found");
            return s;
        }
    }

    @Override
    public void delete(Id<PHD, UUID> id) {
        synchronized (store) {
            PHD s = store.remove(id);
            if (s == null)
                throw new NotFoundException("PHD with id " + id + 
                                            " not found");
        }
    }

}
