//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.a.hola.impl;

import static org.junit.Assert.*;

import java.util.UUID;

import com.hp.api.NotFoundException;

import com.a.hola.model.PHD;
import com.a.hola.api.PHDService;

import com.hp.api.Id;

import org.junit.Before;
import org.junit.Test;

/**
 * Sample test of the PHD service implementation.
 */
public class PHDManagerTest {
  
    private PHDService svc;

    @Before
    public void setUp() {
        svc = new PHDManager();
    }
  
    @Test
    public void basics() {
        PHD s = svc.create("Gizmo");
        assertNotNull("incorrect create", s.getId());
        assertEquals("incorrect get", s, svc.get(s.getId()));
        assertEquals("incorrect name", "Gizmo", s.name());
        svc.delete(s.getId());
        try{
            svc.get(s.getId());
            fail("Expected exception");
        } catch(NotFoundException e) {
            
        }
    }

    @Test
    public void defaults() {
        PHD s = svc.create(null);
        assertNotNull("incorrect id", s.getId());
        assertNotNull("incorrect name", s.name());
    }

    @Test(expected=NotFoundException.class)
    public void notFound() {
        Id<PHD, UUID> id = Id.valueOf(UUID.randomUUID());
        svc.get(id);
    }
}
